### ISSUE TITLE
2. jQuery basic concepts

### ISSUE THREAD

**Issue by oubaka** [oubaka/jqfundamentals-1#1]
https://github.com/oubaka/jqfundamentals-1/blob/master/exercises/js/sandbox.js

You should understand how to select and manipulate elements.

2.1 Selecting
Open the file /exercises/index.html in your browser. Use the file /exercises/js/sandbox.js to accomplish the following:
Select all of the div elements that have a class of “module”.
Come up with three selectors that you could use to get the third item in the #myList unordered list. Which is the best to use? Why?
Select the label for the search input using an attribute selector.
Figure out how many elements on the page are hidden
Figure out how many image elements on the page have an alt attribute.
Select all of the odd table rows in the table body.

2.2 Traversing
Open the file /exercises/index.html in your browser. Use the file /exercises/js/sandbox.js to accomplish the following:
Select all of the image elements on the page; log each image’s alt attribute.
Select the search input text box, then traverse up to the form and add a class to the form.
Select the list item inside #myList that has a class of “current” and remove that class from it; add a class of “current” to the next list item.
Select the select element inside #specials; traverse your way to the submit button.
Select the first list item in the #slideshow element; add the class “current” to it, and then add a class of “disabled” to its sibling elements.

2.3 Manipulating
Open the file /exercises/index.html in your browser. Use the file /exercises/js/sandbox.js to accomplish the following:
Add five new list items to the end of the unordered list #myList.
Remove the odd list items
Add another h2 and another paragraph to the last div.module
Add another option to the select element; give the option the value “Wednesday” 
Add a new div.module to the page after the last one; put a copy of one of the existing images inside of it.

**Comment by segunadeleye** [comment]
- https://github.com/oubaka/jqfundamentals-1/blob/master/exercises/js/sandbox.js#L27
  Selecting by id always returns one element, therefore, there is no need for `[0]`
- https://github.com/oubaka/jqfundamentals-1/blob/master/exercises/js/sandbox.js#L42
  https://github.com/oubaka/jqfundamentals-1/blob/master/exercises/js/sandbox.js#L107
  These elements appears once in the DOM, so there's no need for `[0]`
- https://github.com/oubaka/jqfundamentals-1/blob/master/exercises/js/sandbox.js#L127
  Rather than add each item to the DOM on each iteration, a better approach is to put together the items and add them to the DOM once. For the purpose of optimisation, It is advisable to hit the DOM in as fewer times as possible.
- https://github.com/oubaka/jqfundamentals-1/blob/master/exercises/js/sandbox.js#L153
  Wednesday comes after Tuesday :)
- https://github.com/oubaka/jqfundamentals-1/blob/master/exercises/js/sandbox.js#L162-L163
  Try and do this in just one chain.

**Comment by oubaka** [comment]
Point noted and corrections made as adviced

**Comment by segunadeleye** [comment]
I cannot see the changes you have made. Please confirm that you pushed them.

**Comment by segunadeleye** [comment]
Looks good
